/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

/**
 *
 * @author MARTÍN
 */
public class PantallaInicio extends javax.swing.JFrame {
    
    Ajedrez ajedrez;
    
    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caballo = new javax.swing.JLabel();
        rey = new javax.swing.JLabel();
        saludo = new javax.swing.JLabel();
        jugadorBlancasTexto = new javax.swing.JLabel();
        jugadorBlancasEntrada = new javax.swing.JTextField();
        jugadorNegrasTexto = new javax.swing.JLabel();
        jugadorNegrasEntrada = new javax.swing.JTextField();
        botonJugar = new javax.swing.JButton();
        autorApp = new javax.swing.JLabel();
        autorImagenes = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        listaTiempo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        caballo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Ajedrez\\fotos\\caballo_intro.png")); // NOI18N

        rey.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Ajedrez\\fotos\\rey_intro.png")); // NOI18N

        saludo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saludo.setText("¡Bienvenido! Introduce tus datos para jugar:");

        jugadorBlancasTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jugadorBlancasTexto.setText("Jugador 1 (Piezas blancas): ");

        jugadorBlancasEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jugadorNegrasTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jugadorNegrasTexto.setText("Jugador 2 (Piezas negras): ");

        jugadorNegrasEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botonJugar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonJugar.setText("JUGAR");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        autorApp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        autorApp.setText("Autor: Martín Mato Búa");

        autorImagenes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        autorImagenes.setText("Imágenes: Colin M. L. Burnett");

        etiquetaTiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaTiempo.setText("Tiempo de juego:");

        listaTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 minuto", "3 minutos", "5 minutos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caballo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jugadorBlancasEntrada)
                                    .addComponent(jugadorNegrasEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jugadorBlancasTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jugadorNegrasTexto, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autorImagenes, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(listaTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonJugar)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiquetaTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(rey, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(autorApp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(saludo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(saludo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rey)
                            .addComponent(caballo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadorBlancasTexto)
                        .addGap(18, 18, 18)
                        .addComponent(jugadorBlancasEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jugadorNegrasTexto)
                        .addGap(18, 18, 18)
                        .addComponent(jugadorNegrasEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaTiempo)
                        .addGap(18, 18, 18)
                        .addComponent(listaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(botonJugar)
                        .addGap(30, 30, 30)
                        .addComponent(autorApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(autorImagenes)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
     /*   
        String nombreBlancas = jugadorBlancasEntrada.getText();
        String nombreNegras = jugadorNegrasEntrada.getText();
        
        int opcion = listaTiempo.getSelectedIndex();
     */
     
        String nombreBlancas = "Ron Weasley";
        String nombreNegras = "Minerva McGonagall";
        int opcion = 1;
     
        ajedrez = new Ajedrez(nombreBlancas,nombreNegras, opcion);
        this.dispose();
    }//GEN-LAST:event_botonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorApp;
    private javax.swing.JLabel autorImagenes;
    private javax.swing.JButton botonJugar;
    private javax.swing.JLabel caballo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JTextField jugadorBlancasEntrada;
    private javax.swing.JLabel jugadorBlancasTexto;
    private javax.swing.JTextField jugadorNegrasEntrada;
    private javax.swing.JLabel jugadorNegrasTexto;
    private javax.swing.JComboBox<String> listaTiempo;
    private javax.swing.JLabel rey;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
}
